/* Latitude and longitude of Vancouver*/
export const latVancouver = 49.28;
export const lngVancouver = -123.12;

/* Radius in meters, prioritizes locations within this radius for autocomplete*/
export const searchRadius = 10000; 

/* Average emissions of CO2 generated by typical passenger vehicle 
    Number obtained from https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle
    Converted to kg per km */
export const emissionsProducedKgPerKm = 0.251033884;

/* Default magnitude of zoom in on map */
export const defaultZoomLevel = 13;

export const metresToKm = 0.001;